on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: 🔍 Allow IP
      run: |
        GLOBAL_IP=`curl inet-ip.info`
        curl -X POST https://api.xrea.com/v1/tool/ssh_ip_allow \
        -d "account=wamwam" \
        -d "server_name=s323.xrea.com" \
        -d "api_secret_key=sGTWz9zzgE7oq6jRLs5HPtFSaYjpgGdE" \
        -d "param[addr]=${GLOBAL_IP}"
    
    - name: 📂 Sync files
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        sleep 300
        mkdir -p ~/.ssh
        echo "${SSH_KEY}" > ~/.ssh/id_ed25519_github
        chmod 400 ~/.ssh/id_ed25519_github
        ssh-keyscan s323.xrea.com >> ~/.ssh/known_hosts
        rsync -av ./ wamwam@s323.xrea.com:~/lp-practice-static
